### ISSUE TITLE
proposal: Add X-Request-Id header

### ISSUE THREAD

**Issue by jdolitsky** [kubernetes-helm/chartmuseum#21]
With recent changes (#19) each request is assigned a numeric "RequestId" in order to easily group log lines tied to a request.

My suggestion is to take this one step further, and send the RequestId to the client in the`X-Request-Id` HTTP header for further debugging, correlating client-side requests to associated log lines.

I'd also like to propose using a UUID instead of integer to prevent collisions across replicas.

This gin middleware seems to do everything we need: https://github.com/atarantini/ginrequestid

In addition, we may want to discuss changing the format of log lines, i.e. should we prefix every line with this long UUID, or make it a k/v similar to `"method": "GET"`?

@cjauvin @davidovich thoughts?

**Comment by davidovich** [comment]
I think this is a good idea. I was thinking about this and thought that we should use both approaches, as they serve different use cases. One is for local debugging (the numerical id) and the other is for remote debugging server to client interactions. 

The existing numerical implementation holds the Request ID name, but it should change names, so that this proposal can take its place. 

With this variant, we would keep the log prefix numerical, and also populate, as you suggest, the json k/v UUID request id. The numerical id should never bleed into the header as it is not unique across replicas, but they are unique in the process space where they are observed.

**Comment by davidovich** [comment]
fixed by #23
