### ISSUE TITLE
Question for --allow-overwrite

### ISSUE THREAD

**Issue by hiscal2015** [kubernetes-helm/chartmuseum#33]
Hi,

I'm not sure my question is regarding chart repo or chartmuseum, is it allow to store multiple versions of a chart? For example, I have a chart named nginx, I uploaded version 1.0.0 and 1.0.1, should I see both versions by helm search? Actually, I used --allow-overwrite parameter for chartmuseum, I can see chart 1.0.0.tgz and 1.0.1.tgz were both in the chart storage, but can only see version 1.0.1 by helm search, means only 1.0.1 in index.yaml, is this the expected behavior?

**Comment by jdolitsky** [comment]
@hiscal2015 this is a question about Helm, but more than happy to help out.

You can certainly store multiple versions of a chart in a repository. In order to see all versions of a chart, use the `-l` flag when searching, for example `helm search stable/mysql -l`. If you look at index.yaml you should see both versions.

ChartMuseum's `--allow-overwrite` flag will allow you to re-upload a chart of the same version. For example, if chart-1.0.1.tgz has already been uploaded, you will be able to upload chart-1.0.1.tgz 
 again without error, replacing the one in storage. Without the flag, you will receive an error that the version already exists.

Hope this helps!

**Comment by hiscal2015** [comment]
@jdolitsky Thank you very much, it helps a lot!
